# -*- coding: utf-8 -*-
"""smart internz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192tRmmTIB5Ywk-3pccTncy7RfeC0T1cB
"""



!pip install -q --upgrade gradio

# Import Libraries
import torch
from diffusers import StableDiffusionPipeline
import gradio as gr
from PIL import Image
import os

# Check if CUDA (GPU) is available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# Load Pretrained Stable Diffusion Model
pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to(device)

# Enable optimization for faster generation
pipeline.enable_attention_slicing()
torch.backends.cuda.matmul.allow_tf32 = True

# Function to Generate Fashion Designs and Animation
def generate_fashion_with_animation(prompt, steps=25, frames=5):
    print("Generating fashion design animation for:", prompt)

    # Use a static seed for reproducibility and slight performance boost
    generator = torch.Generator(device).manual_seed(42)

    # Batch generate images for faster processing
    images = pipeline([f"{prompt}, variation {i}" for i in range(frames)], num_inference_steps=steps, generator=generator).images

    # Save the first frame as the main image
    images[0].save("fashion_design.png")

    # Create GIF animation
    gif_path = "fashion_design_animation.gif"
    images[0].save(gif_path, save_all=True, append_images=images[1:], duration=150, loop=0)

    return images[0], gif_path

# Gradio Interface
def main():
    gr.Interface(
        fn=generate_fashion_with_animation,
        inputs=[
            gr.Textbox(label="Fashion Prompt", placeholder="Describe your fashion idea..."),
            gr.Slider(10, 100, value=25, label="Inference Steps"),
            gr.Slider(3, 10, value=5, label="Animation Frames")
        ],
        outputs=["image", gr.Image(label="Animation Preview")],
        title="Glamor AI",
        description="Enter a description of your fashion idea and watch it come to life with an animated GIF!"
    ).launch(share=True)

if __name__ == "__main__":
    main()